corpora:
  bnc:
    name:  "BNC"
    path:  "/storage/users/wingfiel/corpora/BNC/2 Tokenised/BNC.corpus"
    index: "/storage/users/wingfiel/indexes/BNC.freqdist"
  subtitles:
    name:  "BBC"
    path:  "/storage/users/wingfiel/corpora/BBC/4 Tokenised/BBC.corpus"
    index: "/storage/users/wingfiel/indexes/BBC.freqdist"
  ukwac:
    name:  "UKWAC"
    path:  "/storage/users/wingfiel/corpora/UKWAC/3 Tokenised/UKWAC.corpus"
    index: "/storage/users/wingfiel/indexes/UKWAC.freqdist"

models:
  directory: "/storage/users/wingfiel/vectors/"

sensorimotor-norms-location: "/storage/users/wingfiel/experimental_data/FINAL_sensorimotor_norms_for_39707_words.csv"
